### ISSUE TITLE
Enable virtualtext in currentLabelOnly

### ISSUE THREAD

**Issue by ghost** [matsui54/denops-signature_help#26]
## Background
I believe looks cooler than border style.

**Comment by matsui54** [comment]
I reorganized the style configuration to make it more customizable. Can you try the #28 with the following settings?

```vim
let g:signature_help_config = {
      \ contentsStyle: "currentLabel",
      \ viewStyle: "virtual",
      \ }
```

**Comment by matsui54** [comment]
Merged the fix. Please use the settings above.
